### ISSUE TITLE
Fetch Comments Crash

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#15]
Looks like the comment incentives fail to fetch comments sometimes. Use this scenario for debugging and fix the root issue. 

> ```diff
> + Evaluating results. Please wait...
> ```

> I can manually pay out for the assignee (200 USD) https://gnosisscan.io/tx/0x090ed3c34a0cbecbf5cb87d2aa69fffb484551fed1db8f94ff6517f7ee255703

> @FernandVEYRIER if you want the comment incentives as well, we will need to fix where it crashed first. 

> https://github.com/ubiquibot/comment-incentives/actions/runs/7881915632/job/21506313614#step:5:75

> https://github.com/ubiquibot/comment-incentives/blob/626aed050d2040e389608851de73481abb3fd017/src/index.ts#L166

_Originally posted by @pavlovcik in https://github.com/ubiquity/devpool-directory-bounties/issues/14#issuecomment-1940770424_

**Comment by pavlovcik** [comment]
In case you didn't get the notification from the issue specification here is a new tag @FernandVEYRIER

**Comment by FernandVEYRIER** [comment]
@pavlovcik Is there a way to do the testing locally? Or should I create an organization and a repo for testing maybe?

**Comment by pavlovcik** [comment]
The best way is to set up your own repositories yes. I'm not sure if you need to make an organization but to minimize debugging headaches it might be simplest to replicate the current setup.

**Comment by pavlovcik** [comment]
> ```diff
> + Evaluating results. Please wait...
> ```
> 

I need to update an organization secret to the correct key to decode the `evmPrivateKeyEncrypted`

Will retry your other reward from the other repository now since I'm mobile.

**Comment by FernandVEYRIER** [comment]
@pavlovcik Sure no problem. At least it goes beyond the crash that we got before, these logs are after the lines that got fixed!
