### ISSUE TITLE
Permit generated to wrong address

### ISSUE THREAD

**Issue by molecula451** [ubiquibot/comment-incentives#20]
<details>
    <summary>
      <b
        ><h3>
          <a
            href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyOTUwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjUzODU2OTkwMTQ4ODI2MjQ5Nzk0OTczNjAyMzU1Mjc2ODQ2MjU5MTIwNjA4NTAwNTIxNDA0MDA5NzIxNjc5NjM3MDAzMTUzNDI2MTgxIiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgxOTI3NUU5ZkQ3MjE5MDZGMjcxNUQ0Yjc4NjgxYjQ5ZGE1MDg4MTE3IiwicmVxdWVzdGVkQW1vdW50IjoiMjk1MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweDg3NzQ2Mjk4Y2ZkMTRmMTFmOGY4NTNlNDk2ZTc1ZTQ2YmZhYzBmZmEwYjk0NmFjNjJmNDEwYTYyYjkyZDQ1NzAzZmEzMjQ4ZDJjZDhmNGNiOGI4ZTkyZTEwZTk3YTJhMzEyYTkwYTE5YmVhYjgwZThkMDE5YTkwNGUwNjFmYWRiMWIiLCJuZXR3b3JrSWQiOjEwMH1d"
          >
            [ 29.5 WXDAI ]</a
          >
        </h3>
        <h6>@molecula451</h6></b
      >
    </summary>
    <h6>Contributions Overview</h6>
<table><thead>
<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th>
</thead><tbody>
<tr><td>Issue</td><td>Comment</td><td>4</td><td>18.3</td></tr>
<tr><td>Review</td><td>Comment</td><td>3</td><td>11.2</td></tr>
</tbody></table>
    <h6>Conversation Incentives</h6><table><thead><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead><tbody><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1939812859">i'm likely good with `require()` i would focus in gas optimizati...</a></h6></td><td><details><summary>8.8</summary>
<pre>li:
  count: 3
  score: "3"
  words: 3
code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.7</td><td>8.8</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940425294">> custom errors are preferred over require/assert. This definate...</a></h6></td><td><details><summary>5.4</summary>
<pre>code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.73</td><td>5.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940429868">> I believe the contracts is being deployed on Ethereum mainnet....</a></h6></td><td>1.4</td><td>0.45</td><td>1.4</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/issues/895#issuecomment-1940464897">custom erros can also be inside `require()` that's why the chang...</a></h6></td><td><details><summary>2.7</summary>
<pre>code:
  count: 1
  score: "1"
  words: 1
</pre>
</details></td><td>0.51</td><td>2.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1941644623">Please fix the build actions as some are not passing...</a></h6></td><td>1</td><td>0.31</td><td>1</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1943256893">Yeah i think the PR won't make it either as the such refactors s...</a></h6></td><td>7.7</td><td>0.68</td><td>7.7</td></tr><tr><td><h6><a href="https://github.com/ubiquity/ubiquity-dollar/pull/896#issuecomment-1944485579">it looks like it took action on the PR closing but not on the is...</a></h6></td><td>2.5</td><td>0.59</td><td>2.5</td></tr></tbody></table>
  </details>
  
  Clicking on it looks like the bot generated a permit to the wrong address

**Comment by pavlovcik** [comment]
This is a known issue. @gitcoindev any ideas on how to fix it for everyone? Should we just drop the entire table and force re-registration?

**Comment by molecula451** [comment]
drop that nonce meanwhile @pavlovcik

**Comment by gitcoindev** [comment]
@pavlovcik @molecula451 let me check in Supabase directly. In my case wallet id was null and I was able to manually correct the entry. I will check if this is the case for any other users in the database and try to fix this.

**Comment by molecula451** [comment]
lol so due to many refactor the bot catch a wrong address to  me @pavlovcik @gitcoindev i think it'll be good now

**Comment by gitcoindev** [comment]
@molecula451 from what I see your address was pointing to 0x19275E9fD721906F2715D4b78681b49da5088117, which is wallet id 35 in the wallets table and was assigned to a different username (h91....). Now you updated and it was corrected. I have found an old dump somewhere, will now double check other wallets to verify that it does not happen for anyone else. As for me @pavlovcik will have to send this one manually.

**Comment by gitcoindev** [comment]
This will take me a while, as db maps github user ids to wallet table with wallet ids, but extracting should be easy. I will definitely finish today checking this.

**Comment by molecula451** [comment]
i think pavlovick can hook a label here to close to see if we're good to go

**Comment by pavlovcik** [comment]
lol all the specification details racked up a massive reward. Technically you should have used a block quote I guess

**Comment by molecula451** [comment]
yeah it's fixed! the bug now it's check the database for ALL users, to see if they have correct address

**Comment by molecula451** [comment]
lmao i claimed before you posted that message pavlovcik

**Comment by gitcoindev** [comment]
And the unlucky winners are: ['wannacfuture', 'QuintusTheFifth', 'harjaapdhillon16', 'sweetapplepumpkinpie', 'Venoox', 'h918m', 'diamondnegroni', 'starlitnightsky', 'Ameralameri', 'web4er', 'b4s36t4', 'whilefoo', 'devtestubq', 'EtherealGlow']
Their wallet addresses differ from 2023 dump. I sent full details to @pavlovcik and suggest we drop the wallets table and ask everyone to register their wallet address again.
