### ISSUE TITLE
Broken Permit Format

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#3]
- https://github.com/ubiquity/pay.ubq.fi/pull/146 appears to have changed the format that it expects the permits to be encoded in. 
- Example: https://github.com/ubiquity/work.ubq.fi/issues/1#issuecomment-1910279707
   - > "ERROR | INVALID CLAIM DATA PASSED IN URL"

Please match the permit encoding format in this codebase.

**Comment by whilefoo** [comment]
It appears the permit was not generated with new format. I think you haven't merged https://github.com/pavlovcik/ubiquibot-config/pull/7 to this repo

**Comment by pavlovcik** [comment]
Perhaps you can open another pull request to @ubiquibot organization's config?

**Comment by whilefoo** [comment]
Won't we use this repo (`comment-incentives`) for this? It seems weird to have it in config repo

**Comment by pavlovcik** [comment]
I can't load the pull request file changes view from my phone it just breaks so I don't understand the implementation details. Anyways it probably makes sense to just merge in this repository then!

**Comment by whilefoo** [comment]
<img width="1236" alt="image" src="https://github.com/ubiquibot/comment-incentives/assets/139262667/77f77299-0a64-4cc0-aff1-f8eee82ed58d">
I can't make a PR

**Comment by pavlovcik** [comment]
That's weird what about trying to merge to development?

**Comment by whilefoo** [comment]
I think it's because the two repositories don't have a common root commit (https://stackoverflow.com/a/23350970), so the only way is to force push or create new repo

**Comment by pavlovcik** [comment]
Just commit on development and in the commit message you can add a new line 

Resolves #

**Comment by pavlovcik** [comment]
> ### [ [ 38.6 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDQwMDdDRTIwODNjN0YzRTE4MDk3YWVCM0EzOWJiOGVDMTQ5YTM0MWQiLCJyZXF1ZXN0ZWRBbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4ZDlhMWY2NmIwMWZhODE3ZTFjMDhkNDdlMTM1YmY1ZWNhMmRhY2EzMzk3OTZiYWJiYTcwOTEzMWI5NTA2MWJlYjEwMDY1ZGRjN2VjOTA3YWVlNzdjMTA1ZDcxZWMwN2UyNGEwZjQ4ODVkZTRjYzEyNWMxMmNlMjllNTg4MTkzMjQxYiIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> ###### @pavlovcik
> ### [ [ 62.3 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweENlZTMzQzk4NDEwREViZTY3QTMxOUNiOTRGMzllNDAzNDM1RGYzMTkiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4Y2RhM2QxMmMzZTQxMGQzY2EwZTA3NjFhMDE1Y2Q5YWNmNGU5ZWNmMjYyMGVlZTcxNDc3ZWY0MzExM2FhYmMyZTExZmNiMTlmMjRjYjA3ZmI0YzQ2OWE5MzNkYzlhMDA0MTI0MDcxNDVhODE0OWUyYzc3MTRlNzU3ZjlkMGU1YmMxYyIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> ###### @whilefoo

Hey @rndquu @wannacfuture we need to fix the payment permit wallet because these rewards are coming from a non funded wallet. I want to make a new wallet and start issuing these payments again.

**Comment by wannacfuture** [comment]
You just need to change the X25519_PRIVATE_KEY and evmKey in the config.

**Comment by pavlovcik** [comment]
I was never able to successfully regenerate the evm encrypted private key. I might need some help with this but I'll try again tonight. 

@Diamondnegroni will keep you posted on if this is stable

**Comment by rndquu** [comment]
> > ### [ [ 38.6 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDQwMDdDRTIwODNjN0YzRTE4MDk3YWVCM0EzOWJiOGVDMTQ5YTM0MWQiLCJyZXF1ZXN0ZWRBbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4ZDlhMWY2NmIwMWZhODE3ZTFjMDhkNDdlMTM1YmY1ZWNhMmRhY2EzMzk3OTZiYWJiYTcwOTEzMWI5NTA2MWJlYjEwMDY1ZGRjN2VjOTA3YWVlNzdjMTA1ZDcxZWMwN2UyNGEwZjQ4ODVkZTRjYzEyNWMxMmNlMjllNTg4MTkzMjQxYiIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> > ###### @pavlovcik
> > ### [ [ 62.3 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweENlZTMzQzk4NDEwREViZTY3QTMxOUNiOTRGMzllNDAzNDM1RGYzMTkiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4Y2RhM2QxMmMzZTQxMGQzY2EwZTA3NjFhMDE1Y2Q5YWNmNGU5ZWNmMjYyMGVlZTcxNDc3ZWY0MzExM2FhYmMyZTExZmNiMTlmMjRjYjA3ZmI0YzQ2OWE5MzNkYzlhMDA0MTI0MDcxNDVhODE0OWUyYzc3MTRlNzU3ZjlkMGU1YmMxYyIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> > ###### @whilefoo
> 
> Hey @rndquu @wannacfuture we need to fix the payment permit wallet because these rewards are coming from a non funded wallet. I want to make a new wallet and start issuing these payments again.
> 
> @wannacfuture looks like relevance is not multiplying against the formatting score. This is incorrect.

If you want to use a new wallet then you need to:
1. Export evm private key of the new wallet
2. Open https://pay.ubq.fi/keygen
3. Insert `x25519_private_key` in the "X25519_PRIVATE_KEY" field (I've DMed you this value on 25 Dec, check telegram)
4. Insert evm private key in the "PLAIN_TEXT" field
5. Click "Encrypt"
6. Insert the value from the "CIPHER_TEXT" field in the bot's config (not sure where exactly)
