### ISSUE TITLE
Wrong Issue Requested

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#7]
The reason is not clear to me why it would request for "issue 1234" but this is a new problem. 

> @wannacfuture new error that doesn't make any sense to me https://github.com/ubiquibot/comment-incentives/actions/runs/7711668676/job/21017483843

_Originally posted by @pavlovcik in https://github.com/ubiquity/business-development/issues/67#issuecomment-1916817930_

**Comment by wannacfuture** [comment]
Working on it.
