### ISSUE TITLE
Qualitative Score Not Applying Correctly

### ISSUE THREAD

**Issue by pavlovcik** [ubiquibot/comment-incentives#8]
Looks like relevance is not multiplying against the formatting score. This is incorrect. If there are 100 words and the relevance is 0.25, then the total reward should be (with default quantitative scoring settings, which are intentionally set low while we make this stable):

100 words ($10)
times
0.25
= $2.5

> ### [ [ 38.6 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweDQwMDdDRTIwODNjN0YzRTE4MDk3YWVCM0EzOWJiOGVDMTQ5YTM0MWQiLCJyZXF1ZXN0ZWRBbW91bnQiOiIzODYwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4ZDlhMWY2NmIwMWZhODE3ZTFjMDhkNDdlMTM1YmY1ZWNhMmRhY2EzMzk3OTZiYWJiYTcwOTEzMWI5NTA2MWJlYjEwMDY1ZGRjN2VjOTA3YWVlNzdjMTA1ZDcxZWMwN2UyNGEwZjQ4ODVkZTRjYzEyNWMxMmNlMjllNTg4MTkzMjQxYiIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> ###### @pavlovcik
> ### [ [ 62.3 WXDAI ]](https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJub25jZSI6IjI2NTUxNjU5MDUzNjQ1MTE0ODc2Mjc0NzU2MjAxOTMyNjgwNTc3MDE3NjA1Mjc1OTg2OTM2MjcwNzczMzQ0NjE5MjcwOTMwOTAxNzYiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweENlZTMzQzk4NDEwREViZTY3QTMxOUNiOTRGMzllNDAzNDM1RGYzMTkiLCJyZXF1ZXN0ZWRBbW91bnQiOiI2MjMwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4QUNDNDA3NzU3NWNhY2FBQTJDMjM1RmUwNDFEYmQ2RjIxMTZGNDdBOCIsInNpZ25hdHVyZSI6IjB4Y2RhM2QxMmMzZTQxMGQzY2EwZTA3NjFhMDE1Y2Q5YWNmNGU5ZWNmMjYyMGVlZTcxNDc3ZWY0MzExM2FhYmMyZTExZmNiMTlmMjRjYjA3ZmI0YzQ2OWE5MzNkYzlhMDA0MTI0MDcxNDVhODE0OWUyYzc3MTRlNzU3ZjlkMGU1YmMxYyIsIm5ldHdvcmtJZCI6MTAwfV0%3D)
> ###### @whilefoo

**Comment by pavlovcik** [comment]
So basically I tried fixing this and realized the code is so messy that I'm just completely redoing the plugin over at https://github.com/pavlovcik/conversation-rewards

**Comment by gentlementlegen** [comment]
@pavlovcik should be solved by https://github.com/ubiquibot/conversation-rewards/pull/3#issuecomment-2014243670 when online I guess 😄
